from __future__ import annotations

from enum import StrEnum


class ExecutiveState(StrEnum):
    INTAKE = "INTAKE"
    CLARIFICATION_REQUIRED = "CLARIFICATION_REQUIRED"
    CHARTER_DRAFT = "CHARTER_DRAFT"
    AWAITING_CHARTER_APPROVAL = "AWAITING_CHARTER_APPROVAL"
    ACTIVE = "ACTIVE"
    PLANNING = "PLANNING"
    EXECUTING = "EXECUTING"
    REVIEWING = "REVIEWING"
    BLOCKED = "BLOCKED"
    PAUSED = "PAUSED"
    WAITING_FOR_PROVIDER = "WAITING_FOR_PROVIDER"
    WAITING_FOR_USAGE_RESET = "WAITING_FOR_USAGE_RESET"
    WAITING_FOR_FOUNDER = "WAITING_FOR_FOUNDER"
    WAITING_FOR_CREDENTIAL = "WAITING_FOR_CREDENTIAL"
    WAITING_FOR_EXTERNAL_SYSTEM = "WAITING_FOR_EXTERNAL_SYSTEM"
    COMPLETED = "COMPLETED"
    CANCELED = "CANCELED"
    FAILED = "FAILED"


class CharterStatus(StrEnum):
    DRAFT = "DRAFT"
    PROPOSED = "PROPOSED"
    APPROVED = "APPROVED"
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"
    SUPERSEDED = "SUPERSEDED"
    COMPLETED = "COMPLETED"
    CANCELED = "CANCELED"


class DelegationMode(StrEnum):
    ADVISORY = "ADVISORY"
    DELEGATED = "DELEGATED"
    FULL_DELEGATION = "FULL_DELEGATION"


class ValueProvenance(StrEnum):
    EXPLICIT = "EXPLICIT"
    INFERRED_HIGH_CONFIDENCE = "INFERRED_HIGH_CONFIDENCE"
    PROPOSED_ASSUMPTION = "PROPOSED_ASSUMPTION"
    UNRESOLVED = "UNRESOLVED"
    VERIFIED = "VERIFIED"
    RECOMMENDATION = "RECOMMENDATION"
    SUPERSEDED = "SUPERSEDED"


class AuthorityOutcome(StrEnum):
    ALLOWED = "ALLOWED"
    ALLOWED_WITHIN_LIMIT = "ALLOWED_WITHIN_LIMIT"
    REQUIRES_FOUNDER_APPROVAL = "REQUIRES_FOUNDER_APPROVAL"
    DENIED = "DENIED"
    CHARTER_REVISION_REQUIRED = "CHARTER_REVISION_REQUIRED"
    EXPIRED = "EXPIRED"
    REVOKED = "REVOKED"
    INDETERMINATE = "INDETERMINATE"


class ActionCategory(StrEnum):
    ANALYZE = "ANALYZE"
    PLAN = "PLAN"
    DRAFT = "DRAFT"
    READ = "READ"
    WRITE = "WRITE"
    TEST = "TEST"
    REVIEW = "REVIEW"
    REPAIR = "REPAIR"
    COMMIT = "COMMIT"
    PUSH = "PUSH"
    DEPLOY_STAGING = "DEPLOY_STAGING"
    DEPLOY_PRODUCTION = "DEPLOY_PRODUCTION"
    PUBLISH_PRIVATE = "PUBLISH_PRIVATE"
    PUBLISH_PUBLIC = "PUBLISH_PUBLIC"
    PURCHASE = "PURCHASE"
    SPENDING = "SPENDING"
    CREDENTIAL_ACCESS = "CREDENTIAL_ACCESS"
    SECURITY_BOUNDARY_CHANGE = "SECURITY_BOUNDARY_CHANGE"
    HISTORY_REWRITE = "HISTORY_REWRITE"
    LIVE_TRADING = "LIVE_TRADING"
    FINANCIAL_AUTHORITY_CHANGE = "FINANCIAL_AUTHORITY_CHANGE"
    IRREVERSIBLE_DELETE = "IRREVERSIBLE_DELETE"
    CHANGE_GOVERNANCE = "CHANGE_GOVERNANCE"
    EXPAND_SCOPE = "EXPAND_SCOPE"

    # Source-compatible names serialize only to the canonical values above.
    PUBLISH_EXTERNAL = PUBLISH_PUBLIC
    SPEND = SPENDING
    PAID_PROVIDER_USE = SPENDING
    ACCESS_CREDENTIAL = CREDENTIAL_ACCESS
    CHANGE_SECURITY_BOUNDARY = SECURITY_BOUNDARY_CHANGE
    REWRITE_HISTORY = HISTORY_REWRITE
    ENABLE_LIVE_TRADING = LIVE_TRADING
    CHANGE_FINANCIAL_AUTHORITY = FINANCIAL_AUTHORITY_CHANGE
    DELETE_PROTECTED = IRREVERSIBLE_DELETE
    IRREVERSIBLE_DESTRUCTIVE = IRREVERSIBLE_DELETE

    @classmethod
    def _missing_(cls, value: object) -> ActionCategory | None:
        if not isinstance(value, str):
            return None
        legacy = {
            "PUBLISH_EXTERNAL": cls.PUBLISH_PUBLIC,
            "SPEND": cls.SPENDING,
            "PAID_PROVIDER_USE": cls.SPENDING,
            "ACCESS_CREDENTIAL": cls.CREDENTIAL_ACCESS,
            "CHANGE_SECURITY_BOUNDARY": cls.SECURITY_BOUNDARY_CHANGE,
            "REWRITE_HISTORY": cls.HISTORY_REWRITE,
            "ENABLE_LIVE_TRADING": cls.LIVE_TRADING,
            "CHANGE_FINANCIAL_AUTHORITY": cls.FINANCIAL_AUTHORITY_CHANGE,
            "DELETE_PROTECTED": cls.IRREVERSIBLE_DELETE,
            "IRREVERSIBLE_DESTRUCTIVE": cls.IRREVERSIBLE_DELETE,
        }
        return legacy.get(value)


class ActionEffect(StrEnum):
    LOCAL_READ = "LOCAL_READ"
    LOCAL_WRITE = "LOCAL_WRITE"
    SOURCE_EDIT = "SOURCE_EDIT"
    TEST_EXECUTION = "TEST_EXECUTION"
    COMMIT = "COMMIT"
    PUSH = "PUSH"
    DEPLOY_STAGING = "DEPLOY_STAGING"
    DEPLOY_PRODUCTION = "DEPLOY_PRODUCTION"
    PUBLISH_PRIVATE = "PUBLISH_PRIVATE"
    PUBLISH_PUBLIC = "PUBLISH_PUBLIC"
    PURCHASE = "PURCHASE"
    PAID_PROVIDER_USE = "PAID_PROVIDER_USE"
    CREDENTIAL_ACCESS = "CREDENTIAL_ACCESS"
    SECURITY_BOUNDARY_CHANGE = "SECURITY_BOUNDARY_CHANGE"
    HISTORY_REWRITE = "HISTORY_REWRITE"
    LIVE_TRADING = "LIVE_TRADING"
    FINANCIAL_AUTHORITY_CHANGE = "FINANCIAL_AUTHORITY_CHANGE"
    IRREVERSIBLE_DELETE = "IRREVERSIBLE_DELETE"


class ApprovalKind(StrEnum):
    ONE_TIME = "ONE_TIME"
    CHARTER_DURATION = "CHARTER_DURATION"
    TIME_LIMITED = "TIME_LIMITED"
    AMOUNT_LIMITED = "AMOUNT_LIMITED"
    PROVIDER_SPECIFIC = "PROVIDER_SPECIFIC"
    WORKSPACE_SPECIFIC = "WORKSPACE_SPECIFIC"
    ACTION_CATEGORY = "ACTION_CATEGORY"


class FounderApprovalIntent(StrEnum):
    APPROVE_CHARTER = "APPROVE_CHARTER"
    APPROVE_ACTION = "APPROVE_ACTION"


class TaskStatus(StrEnum):
    PROPOSED = "PROPOSED"
    READY = "READY"
    ASSIGNED = "ASSIGNED"
    LAUNCH_CLAIMED = "LAUNCH_CLAIMED"
    EXECUTION_STARTED = "EXECUTION_STARTED"
    RUNNING = "RUNNING"
    COMPLETION_PENDING = "COMPLETION_PENDING"
    WAITING = "WAITING"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    REPAIR_REQUIRED = "REPAIR_REQUIRED"
    COMPLETED = "COMPLETED"
    BLOCKED = "BLOCKED"
    FAILED = "FAILED"
    CANCELED = "CANCELED"
    UNCERTAIN = "UNCERTAIN"
    SKIPPED = "SKIPPED"


class ReviewPolicy(StrEnum):
    SELF_VERIFICATION = "SELF_VERIFICATION"
    AUTOMATED = "AUTOMATED"
    INDEPENDENT_SPECIALIST = "INDEPENDENT_SPECIALIST"
    SECURITY = "SECURITY"
    FOUNDER = "FOUNDER"


class MemoryKind(StrEnum):
    FACT = "FACT"
    DECISION = "DECISION"
    ASSUMPTION = "ASSUMPTION"
    QUESTION = "QUESTION"
    APPROVAL = "APPROVAL"
    OUTCOME = "OUTCOME"
    EVIDENCE = "EVIDENCE"
    BLOCKER = "BLOCKER"
    LESSON = "LESSON"
    FOUNDER_PREFERENCE = "FOUNDER_PREFERENCE"
