from __future__ import annotations

from enum import StrEnum


class ProviderClassification(StrEnum):
    LOCAL = "LOCAL"
    REMOTE = "REMOTE"


class SessionModel(StrEnum):
    STATELESS = "STATELESS"
    RESUMABLE = "RESUMABLE"
    PERSISTENT = "PERSISTENT"


class CostMode(StrEnum):
    FREE = "FREE"
    INCLUDED = "INCLUDED"
    PAID = "PAID"


class HealthState(StrEnum):
    READY = "READY"
    DEGRADED = "DEGRADED"
    UNAVAILABLE = "UNAVAILABLE"
    AUTHENTICATION_REQUIRED = "AUTHENTICATION_REQUIRED"


class ProviderSessionState(StrEnum):
    READY = "READY"
    BUSY = "BUSY"
    DISCONNECTED = "DISCONNECTED"
    PAUSED = "PAUSED"
    CLOSED = "CLOSED"


class AssignmentRole(StrEnum):
    PLANNER = "PLANNER"
    IMPLEMENTER = "IMPLEMENTER"
    REVIEWER = "REVIEWER"
    RESEARCHER = "RESEARCHER"
    TESTER = "TESTER"
    DOCUMENTATION_SPECIALIST = "DOCUMENTATION_SPECIALIST"


class WorkflowState(StrEnum):
    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    CANCELED = "CANCELED"
    SUPERSEDED = "SUPERSEDED"


class WorkItemState(StrEnum):
    PROPOSED = "PROPOSED"
    READY = "READY"
    ASSIGNED = "ASSIGNED"
    ACTIVE = "ACTIVE"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    REPAIR_REQUIRED = "REPAIR_REQUIRED"
    COMPLETED = "COMPLETED"
    CANCELED = "CANCELED"
    BLOCKED = "BLOCKED"


class AssignmentState(StrEnum):
    PROPOSED = "PROPOSED"
    READY = "READY"
    PAUSED = "PAUSED"
    WAITING_FOR_USAGE_RESET = "WAITING_FOR_USAGE_RESET"
    LAUNCH_CLAIMED = "LAUNCH_CLAIMED"
    RUNNING = "RUNNING"
    CANCELLATION_CLAIMED = "CANCELLATION_CLAIMED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    REPAIR_REQUIRED = "REPAIR_REQUIRED"
    COMPLETED = "COMPLETED"
    CANCELED = "CANCELED"
    FAILED = "FAILED"
    UNCERTAIN = "UNCERTAIN"


class AttemptState(StrEnum):
    RESERVED = "RESERVED"
    LAUNCH_CLAIMED = "LAUNCH_CLAIMED"
    RUNNING = "RUNNING"
    CANCELLATION_CLAIMED = "CANCELLATION_CLAIMED"
    COMPLETED = "COMPLETED"
    CANCELED = "CANCELED"
    FAILED = "FAILED"
    UNCERTAIN = "UNCERTAIN"


class ReviewState(StrEnum):
    PENDING = "PENDING"
    ACTIVE = "ACTIVE"
    ACCEPTED = "ACCEPTED"
    REPAIR_REQUIRED = "REPAIR_REQUIRED"
    REJECTED = "REJECTED"
    FAILED = "FAILED"


class EvidenceState(StrEnum):
    UNTRUSTED = "UNTRUSTED"
    VALIDATED = "VALIDATED"
    REJECTED = "REJECTED"


class EvidenceReferenceKind(StrEnum):
    LOCAL_PROTECTED_ARTIFACT = "LOCAL_PROTECTED_ARTIFACT"
    REMOTE_STRUCTURED_EVIDENCE = "REMOTE_STRUCTURED_EVIDENCE"


class EvidenceReferenceState(StrEnum):
    VALIDATED = "VALIDATED"
    REJECTED = "REJECTED"


class ReservationMode(StrEnum):
    READ_ONLY = "READ_ONLY"
    WRITE = "WRITE"


class ReservationState(StrEnum):
    ACTIVE = "ACTIVE"
    RELEASED = "RELEASED"
    STALE = "STALE"
    UNCERTAIN = "UNCERTAIN"


class PauseCode(StrEnum):
    USAGE_EXHAUSTED = "USAGE_EXHAUSTED"
    FOUNDER_REQUEST = "FOUNDER_REQUEST"
    PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE"
    PROCESS_CRASH = "PROCESS_CRASH"
    WORKSPACE_CONFLICT = "WORKSPACE_CONFLICT"
    AUTHORITY_REVALIDATION = "AUTHORITY_REVALIDATION"
    UNCERTAIN_EXTERNAL_EFFECT = "UNCERTAIN_EXTERNAL_EFFECT"


class DelegatedModeState(StrEnum):
    ACTIVE = "ACTIVE"
    REVOKED = "REVOKED"
    EXPIRED = "EXPIRED"
    SUPERSEDED = "SUPERSEDED"


class PresentationMode(StrEnum):
    HIDDEN = "HIDDEN"
    COMPACT = "COMPACT"
    CONVERSATION = "CONVERSATION"
    ANALYST = "ANALYST"
