#!/usr/bin/env bash
# Deterministic foundation checks for DarkSage. Run locally or in CI (see
# .github/workflows/ci.yml, job "foundation-checks"). Exits non-zero on any failure.
set -u
fail=0

log_fail() { echo "FAIL: $1"; fail=1; }
log_ok()   { echo "OK: $1"; }

TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

# --- 1. Required directories survive a fresh checkout -----------------------
for d in ai apps backend shared tests; do
  if [ -d "$d" ]; then
    log_ok "directory exists: $d"
  else
    log_fail "missing required directory: $d"
  fi
done

# --- 2. Local coding-tool config is git-ignored at the project level --------
if git check-ignore -q .claude/settings.local.json 2>/dev/null; then
  log_ok ".claude/settings.local.json is git-ignored"
else
  log_fail ".claude/settings.local.json is NOT git-ignored by project .gitignore"
fi

if git check-ignore -q CLAUDE.md 2>/dev/null; then
  log_ok "CLAUDE.md is git-ignored"
else
  log_fail "CLAUDE.md is NOT git-ignored by project .gitignore"
fi

# --- 3. Canonical TradeValidationPipeline: exact whole-block comparison -----
# Every fenced pipeline block must match docs/pipeline-stages.txt EXACTLY —
# same line count, same stage names, same order. No head -n / partial
# comparison: a short, long, renamed, reordered, or duplicated block all fail.
CANON="docs/pipeline-stages.txt"
if [ ! -f "$CANON" ]; then
  log_fail "missing canonical stage list: $CANON"
else
  CANON_COUNT=$(wc -l < "$CANON" | tr -d ' ')

  extract_fences() {
    # $1 = source file, $2 = output dir. Writes each fenced ``` block to
    # outdir/fence_N.txt, normalized: strip leading "→ ", trailing \r, trailing whitespace.
    awk -v outdir="$2" '
      /^```/ { if (in_block) { in_block=0; n++ } else { in_block=1; next } }
      in_block {
        line=$0
        sub(/^→ /, "", line)
        gsub(/\r$/, "", line)
        sub(/[ \t]+$/, "", line)
        print line > (outdir "/fence_" n ".txt")
      }
    ' "$1"
  }

  check_pipeline_blocks_exact() {
    file="$1"
    label="$2"
    fdir="$TMPDIR/fences_$(basename "$file")"
    mkdir -p "$fdir"
    extract_fences "$file" "$fdir"
    found=0
    idx=0
    for block in "$fdir"/fence_*.txt; do
      [ -f "$block" ] || continue
      first_line=$(head -n 1 "$block")
      [ "$first_line" = "AI / Strategy Engine" ] || continue
      idx=$((idx + 1))
      found=1
      actual_count=$(wc -l < "$block" | tr -d ' ')
      if [ "$actual_count" -ne "$CANON_COUNT" ]; then
        log_fail "$label: pipeline block #$idx has $actual_count line(s), expected exactly $CANON_COUNT (missing, extra, or duplicated stage)"
        continue
      fi
      if diff -q "$block" "$CANON" > /dev/null 2>&1; then
        log_ok "$label: pipeline block #$idx matches the canonical $CANON_COUNT-stage pipeline exactly, in order"
      else
        log_fail "$label: pipeline block #$idx differs from the canonical pipeline (stage renamed or reordered)"
        echo "  --- expected ($CANON) ---"
        sed 's/^/    /' "$CANON"
        echo "  --- found (block #$idx in $file) ---"
        sed 's/^/    /' "$block"
      fi
    done
    if [ "$found" -eq 0 ]; then
      log_fail "$label: no canonical-pipeline fenced block found (expected at least one starting with 'AI / Strategy Engine')"
    fi
  }

  check_pointer_only() {
    file="$1"
    label="$2"
    if ! grep -q "TradeValidationPipeline" "$file"; then
      log_fail "$label does not reference the canonical TradeValidationPipeline at all"
      return
    fi
    if grep -qE '(Signal Validator|Strategy Validation|Risk Engine).*→|→.*(Signal Validator|Strategy Validation|Risk Engine)' "$file"; then
      log_fail "$label appears to repeat an abbreviated/partial pipeline instead of pointing to ARCHITECTURE.md §14"
    else
      log_ok "$label references the canonical pipeline as a bare pointer (no partial repeat)"
    fi
  }

  check_pipeline_blocks_exact "ARCHITECTURE.md" "ARCHITECTURE.md §14 (canonical source)"
  check_pipeline_blocks_exact "PROJECT_SPEC.md" "PROJECT_SPEC.md"
  check_pointer_only "TRADING_RULES.md" "TRADING_RULES.md"
  check_pointer_only "SECURITY_RULES.md" "SECURITY_RULES.md"
  check_pointer_only "ROADMAP.md" "ROADMAP.md"
fi

# --- 4. Prohibited development-assistant term scan --------------------------
# Blocklist is deliberately narrow: specific coding-assistant product/vendor
# names and attribution phrasing only. Legitimate product-level AI provider
# references (OpenAI, Anthropic, Gemini, local AI, Sage AI) are never matched
# by these patterns and must never be added to them.
NAME_PATTERN='\b(claude|codex|chatgpt|gpt|ecc)\b'
PHRASE_PATTERN='generated by (an )?AI|reviewed by (an )?AI|AI-authored|AI generated|AI-generated|AI coding assistant|AI coding assistance|machine generated|machine-generated'
# Exclusions, each with a reason a reviewer can audit:
#   - this script: its own pattern definitions must contain the blocked words to check for them
#   - .gitignore: contains the literal, mechanical path ".claude/" for a local ignore rule,
#     not prose attribution
EXCLUDE_PATHS=("scripts/verify-foundation.sh" ".gitignore")

hit=0
while IFS= read -r f; do
  skip=0
  for ex in "${EXCLUDE_PATHS[@]}"; do
    [ "$f" = "$ex" ] && skip=1
  done
  [ "$skip" = 1 ] && continue
  if grep -IlqiE "$NAME_PATTERN|$PHRASE_PATTERN" "$f" 2>/dev/null; then
    echo "  possible hit: $f"
    grep -inE "$NAME_PATTERN|$PHRASE_PATTERN" "$f" | sed 's/^/    /'
    hit=1
  fi
done < <(git ls-files --cached --others --exclude-standard)

if [ "$hit" = 1 ]; then
  log_fail "prohibited development-assistant term or attribution phrase found in the committed tree (see above)"
else
  log_ok "no prohibited development-assistant terms or attribution phrases found in the committed tree"
fi

echo
if [ "$fail" = 0 ]; then
  echo "All foundation checks passed."
else
  echo "One or more foundation checks failed."
fi
exit $fail
